minimumReleaseAgeExclude:
  - '@interop/did-web-resolver@6.1.0'
  - '@interop/data-integrity-core@6.1.0'
  - '@interop/did-io@4.0.1'
  - '@interop/did-method-key@7.1.0'
  - '@interop/ed25519-verification-key@7.0.1'
  - '@typescript-eslint/eslint-plugin@8.60.1'
  - '@typescript-eslint/parser@8.60.1'
  - '@typescript-eslint/project-service@8.60.1'
  - '@typescript-eslint/scope-manager@8.60.1'
  - '@typescript-eslint/tsconfig-utils@8.60.1'
  - '@typescript-eslint/type-utils@8.60.1'
  - '@typescript-eslint/types@8.60.1'
  - '@typescript-eslint/typescript-estree@8.60.1'
  - '@typescript-eslint/utils@8.60.1'
  - '@typescript-eslint/visitor-keys@8.60.1'
  - '@vitest/coverage-v8@4.1.8'
  - '@vitest/expect@4.1.8'
  - '@vitest/mocker@4.1.8'
  - '@vitest/pretty-format@4.1.8'
  - '@vitest/runner@4.1.8'
  - '@vitest/snapshot@4.1.8'
  - '@vitest/spy@4.1.8'
  - '@vitest/utils@4.1.8'
  - typescript-eslint@8.60.1
  - vite@8.0.16
  - vitest@4.1.8
