declare module '@digitalcredentials/did-io';
declare module '@digitalcredentials/vc';
declare module '@digitalbazaar/vc-bitstring-status-list-context';
declare module '@digitalcredentials/vc-status-list';
declare module '@digitalbazaar/vc-status-list-context';
declare module '@digitalcredentials/did-method-web';
declare module '@digitalbazaar/data-integrity-context';
declare module '@digitalcredentials/ed25519-signature-2020';
declare module '@digitalcredentials/x25519-key-agreement-key-2020';
declare module 'credentials-context';
declare module 'jsonld-document-loader';
declare module 'did-context';
declare module 'ed25519-signature-2020-context';
declare module 'x25519-key-agreement-2020-context';
declare module '@digitalcredentials/open-badges-context';
declare module '@digitalcredentials/credentials-v2-context';
declare module '@digitalbazaar/zcap-context'
